### ISSUE TITLE
stellar_sigmacorr = stellar_sigma

### ISSUE THREAD

**Issue by marktgraham** [sdss/marvin#411] opened 2018-05-29 09:57 UTC
For MPL-6, stellar_sigmacorr is identical to stellar_sigma. I assume both are equal to the uncorrected stellar_sigma. For example, these statements are true:

np.min(np.array(maps['stellar_sigma']) == np.array(maps['stellar_sigmacorr']))) = True
np.min(np.array(maps.stellar_sigma) == np.array(maps.stellar_sigmacorr))) = True

**Comment by havok2063** [comment] 2018-05-29 19:57
Hi Mark, 

I'm not sure how you are doing the comparison but if you plot the two maps, they appear to be different.  

```
maps = Maps('8485-1901')
ss = maps.stellar_sigma
sc = maps.stellar_sigmacorr
ss.plot()
sc.plot()
```
I also tried a boolean comparison and there are several sections of the array that are not equal (those not equal to 34)
```
sum(ss == sc)
array([34, 34, 34, 34, 34, 34, 30, 28, 21, 20, 17, 15, 14, 13, 13, 10, 13,
       13, 13, 13, 11, 13, 15, 17, 18, 21, 25, 25, 32, 34, 34, 34, 34, 34])
```
Just to be safe, I also checked the original FITS file data for a MAPS and get the same result.

It looks like if you tried `np.min`, you may have pulled out a corner or edge of the map, in which case those values would be true, since they are outside the region of the IFU bundle.  

But thanks for doing this check again.  We can never be too sure and always need people vetting what we've done.  :) Let us know if you have find anything else!

**Comment by marktgraham** [comment] 2018-05-30 08:58
Hi Brian,

Thanks for getting back to me, but I think I am still having issues. I've checked maps. datamodel and stellar_sigmacorr seems to be missing:

....
 <Property 'stellar_vel', channel='None', release='2.1.3', unit='km / s'>,
 <Property 'stellar_sigma', channel='None', release='2.1.3', unit='km / s'>,
 <Property 'stellar_cont_fresid', channel='68th_percentile', release='2.1.3', unit=''>,
 <Property 'stellar_cont_fresid', channel='99th_percentile', release='2.1.3', unit=''>,
....

I think what is happening is when I select stellar_sigmacorr, it finds the nearest property which is just stellar_sigma. So when I try to plot stellar_sigmacorr, it displays stellar_sigma. I've checked and I am using the latest version of Marvin...

**Comment by marktgraham** [comment] 2018-05-30 15:48
Hi Brett,

Thanks for getting back to me, I *thought* I had the latest version, but I ran pip install --upgrade sdss-marvin again and it seemed to update a few things this time.

I now have `stellar_sigmacorr` in `maps.datamodel`: 
...
<Property 'stellar_vel', channel='None', release='2.0.2', unit='km / s'>, 
<Property 'stellar_sigma', channel='None', release='2.0.2', unit='km / s'>, 
<Property 'stellar_sigmacorr', channel='None', release='2.0.2', unit='km / s'>, 
<Property 'stellar_cont_fresid', channel='68th_percentile', release='2.0.2', unit=''>,
...

but I'm now having the problem I originally thought I was having i.e. stellar_sigmacorr = stellar_sigma. The output of `sum(maps.stellar_sigma == maps.stellar_sigmacorr)` is:

[74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74
 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74
 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74 74
 74 74]

Also, `maps.data_origin` returns `api` so I'm using the remote data.

Any ideas?

Cheers,
Mark

**Comment by havok2063** [comment] 2018-05-30 15:51
Hi Mark, 

Can you tell us which galaxy you are using in these examples?

Cheers, Brian

**Comment by marktgraham** [comment] 2018-05-30 16:17
Hi Brian,

Above is for 7495-12701, I've also tried 7495-6101, 7815-6102 and 7977-6103. None of these galaxies are special in any way, I've just picked them at random. Also, I've checked MPL-5 and MPL-6 and also the 'SPX' and 'VOR10' binning types, and I get the same result. (I can't try MPL-6 and VOR10 as I get this error: `marvin.core.exceptions.MarvinError: found a problem when checking if remote maps exists: Something went wrong on the server side: Failed to retrieve maps 7495-12701: Specified bintype VOR10 is not available in the DB.`)

**Comment by havok2063** [comment] 2018-05-30 16:55
Hi Mark, 

Great thanks.  I can recreate it with 7495-12701 and 8485-1901.  When I access the maps via the files, it seems to work correctly.  However accessing them remotely returns the same thing for `stellar_sigmacorr` and `stellar_sigma`.  It also works correctly when I access them directly on the Utah server using the database.  So it might be something relating to the datamodel when used in remote mode.  We'll keep looking into it.  Reopening this.  

Cheers, Brian

**Comment by havok2063** [comment] 2018-05-30 21:39
I've found the issue.  The problem was during remote calls, the map channel name, which are `None` for the `stellar_XX` parameters was being coerced to a string.  This messed up the property+channel name which caused the datamodel to pull out `stellar_sigma` instead of `stellar_sigmacorr`.  Presumably this was also the case for other maps with no channels.  This has been fixed now.  As soon as this gets pushed, we'll release another patch soon and I'll close this.

**Comment by bretthandrews** [comment] 2018-05-31 00:53
Do we want to pull from datamodel with `exact=True` so that it doesn't do a fuzzy search on the backend?

**Comment by havok2063** [comment] 2018-05-31 13:52
We could.  We know Marvin itself is always exact.  If we change it in `maps.getMap` in the API, then anyone who types in the API directly will have to be exact.   But I think the problem is fixed.  The issue wasn't necessarily exactness.  We were getting `stellar_sigmacorr_None`.  `stellar_sigma` and `stellar_sigmacorr` resolved correctly.

**Closed** 2019-03-11 18:18 UTC
Labels: bug
