### ISSUE TITLE
Marvin error when downloading images

### ISSUE THREAD

**Issue by goyarzun** [sdss/marvin#218] opened 2017-04-08 18:22 UTC
Hi guys,

I am trying to download Marvin images, but I keep getting an error. I have tried with python2 and python3, but neither works. I attach the errors. By the way, data cube downloads work fine. Thanks!

Grecco

[python2.pdf](https://github.com/sdss/marvin/files/907721/python2.pdf)
[python3.pdf](https://github.com/sdss/marvin/files/907722/python3.pdf)

**Comment by goyarzun** [comment] 2017-04-08 18:53
It seems marvin was down, so it now works with python2. Still no luck when using python3, though.

**Comment by bretthandrews** [comment] 2017-04-10 14:50
Hi Grecco,

We sorry that you experienced these difficulties, and we really appreciate that you brought them to our attention with such detailed bug reports.

The problem is that SDSS Access requires your `~/.netrc` file has a certain set of read/write/exceute permissions. In the terminal, type `chmod 600 ~/.netrc` to set it so that only the owner (you) can read and write to this file. This should solve your problem in Python 3 and will eliminate the need for you to interactively enter a username and password in Python 2. 

Cheers,
Brett

**Comment by bretthandrews** [comment] 2017-04-10 15:34
Fixed with six.py

**Closed by bretthandrews** 2017-04-10 15:34 UTC
Labels: bug, marvin-api, marvin-tools, priority-medium, python3

**Comment by havok2063** [comment] 2017-04-10 18:36
Did you write tests for this?  If not, can you?  Regardless if it's an easy fix, we should get into the habit of it.  I started it in here with the last python 2/3 fix I needed to make.  You can piggyback off that.

**Comment by bretthandrews** [comment] 2017-04-11 20:41
The problem was that the code had previously used the Python 2 builtin function `raw_input()`, which was renamed `input()` in Python 3. I fixed this by importing the `input()` function from `six.py` and changing `raw_input()` to `input()`. Now the problem with testing this is that we're basically testing whether the `six.py` correctly determines the Python version in use and whether the Python builtin functions `raw_input()` and `input()` work. This is beyond the scope of our test suite. The solution would be to mock the interactive input but that would be side-stepping the original problem.

**Comment by havok2063** [comment] 2017-04-11 20:45
We probably don't need to go that far.  I think we can just write some tests in sdss_access that make sure that the correct output is returned when using six's `input`.  Just to test that it does indeed work in both python 2 and 3.  And will in the future regardless of changes. Know what I mean?

**Comment by bretthandrews** [comment] 2017-04-11 20:49
1. I don't think that we should test every function in heavily-used packages.
2. Testing `input()` is really difficult because you're trying to test whether an interactive feature returns the correct response in an automated testing suite. Usually people assume that the python builtins work and work around the manual nature of `input` or `stdin`.

**Comment by bretthandrews** [comment] 2017-04-12 14:55
I was able to test that pytest would raise an IOError or OSError due to the generation of the prompt see sdss/sdss_access@97fe168446929f
