### ISSUE TITLE
Error collecting maps from API 

### ISSUE THREAD

**Issue by stirfryannie** [sdss/marvin#715] opened 2020-10-27 16:08 UTC
Error thrown when collecting maps from the API. Started in the past week (everything ran fine last week).

Error attached below:

```
File "mcmc_script_v2_2.py", line 201, in <module>
    gal.get_data()
  File "/home/sc381/Desktop/modelling/class_manga_gal_v10_1.py", line 136, in get_data
    vel = maps.stellar_vel
  File "/home/sc381/anaconda3/lib/python3.7/site-packages/marvin/tools/maps.py", line 140, in _getattr_
    return self.getMap(value)
  File "/home/sc381/anaconda3/lib/python3.7/site-packages/marvin/tools/maps.py", line 634, in getMap
    return marvin.tools.quantities.Map.from_maps(self, best)
  File "/home/sc381/anaconda3/lib/python3.7/site-packages/marvin/tools/quantities/map.py", line 224, in from_maps
    value, ivar, mask = cls._get_map_from_api(maps, prop)
  File "/home/sc381/anaconda3/lib/python3.7/site-packages/marvin/tools/quantities/map.py", line 325, in _get_map_from_api
    'found a problem when getting the map: {0}'.format(str(ee)))
marvin.core.exceptions.MarvinError: found a problem when getting the map: 409.
```

**Comment by stirfryannie** [comment] 2020-10-27 16:18
Considered whether I had an expired token so refreshed the login and tried to access a cube from the API and received extra errors, as below:

>>> cube = marvin.tools.cube.Cube('8485-1901', mode='remote')
[ERROR]: Traceback (most recent call last):
  File "/home/sc381/anaconda3/lib/python3.7/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 200, in _checkResponse
    isbad = response.raise_for_status()
  File "/home/sc381/anaconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: CONFLICT for url: https://sas.sdss.org/marvin/api/cubes/8485-1901/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sc381/anaconda3/lib/python3.7/site-packages/marvin/tools/cube.py", line 240, in _load_cube_from_api
    response = self._toolInteraction(url.format(name=self.plateifu))
  File "/home/sc381/anaconda3/lib/python3.7/site-packages/marvin/tools/core.py", line 134, in _toolInteraction
    return marvin.api.api.Interaction(url, params=params)
  File "/home/sc381/anaconda3/lib/python3.7/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 56, in __init__
    self._sendRequest(request_type)
  File "/home/sc381/anaconda3/lib/python3.7/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 294, in _sendRequest
    self._checkResponse(self._response)
  File "/home/sc381/anaconda3/lib/python3.7/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 204, in _checkResponse
    self.statuscodes[response.status_code])
KeyError: 409

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sc381/anaconda3/lib/python3.7/site-packages/marvin/tools/cube.py", line 78, in __init__
    self._load_cube_from_api()
  File "/home/sc381/anaconda3/lib/python3.7/site-packages/marvin/tools/cube.py", line 243, in _load_cube_from_api
    'exists: {0}'.format(str(ee)))
marvin.core.exceptions.MarvinError: found a problem when checking if remote cube exists: 409.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

**Comment by havok2063** [comment] 2020-10-27 17:42
Hi @stirfryannie I'll try to take a look.  What version of marvin are you using?  Which data release and galaxy are you trying to access?

**Comment by stirfryannie** [comment] 2020-10-27 17:55
Hey Brian, 

Thanks so much. 

I'm using version 2.5.0
I haven't updated this since everything was last working fine. 

I'm accessing MPL-10 
Again, this was accessible last week, and haven't changed anything

The original error was accessing "10001-12704", but also got the same errors trying to access a Cube for "8485-1901"

Hope this helps you look into it.

**Comment by margudo** [comment] 2020-10-27 18:19
Hello, 
I saw this error in Slack and I was going to open a ticket. 
To provide more information, I can access the same data in DR15 release, but not for MPL-10. 
When I do: 
`config.release = 'MPL-10'` 
And then:
`cube = Cube('8485-1901', mode='remote')`
I'm getting the following error message:

`[ERROR]: Traceback (most recent call last):
  File "/home/maria/.local/lib/python3.6/site-packages/brain/api/api.py", line 201, in _checkResponse
    isbad = response.raise_for_status()
  File "/home/maria/.local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: CONFLICT for url: https://sas.sdss.org/marvin/api/cubes/8485-1901/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maria/.local/lib/python3.6/site-packages/marvin/tools/cube.py", line 240, in _load_cube_from_api
    response = self._toolInteraction(url.format(name=self.plateifu))
  File "/home/maria/.local/lib/python3.6/site-packages/marvin/tools/core.py", line 134, in _toolInteraction
    return marvin.api.api.Interaction(url, params=params)
  File "/home/maria/.local/lib/python3.6/site-packages/brain/api/api.py", line 57, in __init__
    self._sendRequest(request_type)
  File "/home/maria/.local/lib/python3.6/site-packages/brain/api/api.py", line 295, in _sendRequest
    self._checkResponse(self._response)
  File "/home/maria/.local/lib/python3.6/site-packages/brain/api/api.py", line 235, in _checkResponse
    raise BrainError('Requests Http Status Error: {0}\n{1}'.format(http, errmsg))
brain.core.exceptions.BrainError: Requests Http Status Error: 409 Client Error: CONFLICT for url: https://sas.sdss.org/marvin/api/cubes/8485-1901/
Error: data release MPL-10 no longer supported by the Marvin API. Update to a later MPL or use Marvin's local file access mode instead.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maria/.local/lib/python3.6/site-packages/marvin/tools/cube.py", line 78, in __init__
    self._load_cube_from_api()
  File "/home/maria/.local/lib/python3.6/site-packages/marvin/tools/cube.py", line 243, in _load_cube_from_api
    'exists: {0}'.format(str(ee)))
marvin.core.exceptions.MarvinError: found a problem when checking if remote cube exists: Requests Http Status Error: 409 Client Error: CONFLICT for url: https://sas.sdss.org/marvin/api/cubes/8485-1901/
Error: data release MPL-10 no longer supported by the Marvin API. Update to a later MPL or use Marvin's local file access mode instead.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

>>> Sentry responded with an API error: RateLimited(None)
["BrainError: Requests Http Status Error: 409 Client Error: CONFLICT for url: https://sas.sdss.org/marvin/api/cubes/8485-1901/\nError: data release MPL-10 no longer supported by the Marvin API. Update to a later MPL or use Marvin's local file access mode instead.", '  File "marvin/tools/cube.py", line 240, in _load_cube_from_api', '  File "marvin/tools/core.py", line 134, in _toolInteraction', '  File "brain/api/api.py", line 57, in __init__', '  File "brain/api/api.py", line 295, in _sendRequest', '  File "brain/api/api.py", line 235, in _checkResponse']
`

**Comment by havok2063** [comment] 2020-10-28 17:35
Hi @stirfryannie, 

So I tried this out in a fresh environment and can't reproduce your error.   I originally used the latest `marvin 2.5.2` and was successful, then I reinstalled `marvin 2.5.0` and was it also worked.  Your error makes me think there's a possible conflict between the version of marvin you are using and the version of marvin running the remote server.  Can you try updating to `marvin 2.5.2` and let me know if you still have the same problem?

```
import marvin
marvin.__version__
'2.5.0'

from marvin.tools import Cube, Maps
maps=Maps('10001-12704')
maps
<Marvin Maps (plateifu='10001-12704', mode='remote', data_origin='api', bintype='HYB10', template='MILESHC-MASTARHC2')>

maps.release
'MPL-10'

st=maps.stellar_vel
st
<Marvin Map (property='stellar_vel')>
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] km / s

cube=Cube('8485-1901', mode='remote')
cube
<Marvin Cube (plateifu='8485-1901', mode='remote', data_origin='api')> 
```

**Comment by stirfryannie** [comment] 2020-10-28 22:37
Hi Brian, 

Updating to 2.5.2 seems to have solved the issue and everything is running fine again. Thanks so much. Strange that this happened, was something changed on the remote server in the past few days? Regardless, this should hopefully be solved now on my end at least. Thanks again

**Comment by havok2063** [comment] 2020-10-29 19:55
Hi @stirfryannie, 

I don't think the server has been updated in the past few days.  The last update and restart was at least a few weeks ago.   It's possible there's still some underlying hidden bug, but updating further obscures it.  I'll close this issue for now.  If you encounter it again feel free to file a new issue and I'll take a deeper look.

**Closed by havok2063** 2020-10-29 19:55 UTC
