### ISSUE TITLE
Incorrect MANGAID and PLATEIFU in maps header

### ISSUE THREAD

**Issue by roberid** [sdss/marvin#662] opened 2019-06-11 15:11 UTC
**Describe the bug**
I've noticed for some observations the maps header lists the wrong MANGAID and PLATEIFU. 

**To Reproduce**
For example, I get the following:

In:  maps = marvin.tools.Maps(mangaid="1-404152")

In:  cube = marvin.tools.Cube(mangaid="1-404152")

In:  maps.header["MANGAID"]
Out:  '1-209232'

In:  cube.header["MANGAID"]
Out:  '1-404152'

In:  maps.header["PLATEIFU"]
Out:  '8485-1901'

In:  cube.header["PLATEIFU"]
Out:  '8949-12703'

**Expected behavior**
As can be seen, the maps header contains the incorrect IDs but the cube header contains the correct IDs.  I also noticed that the (incorrect) IDs contained in the maps header are the same IDs using the the "Getting Started" section of the online Marvin docs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 27
 - Browser Chromium
 - Version 69.0.3497.100

**Additional context**

**Comment by roberid** [comment] 2019-06-11 15:40
I am using marvin 2.3.2 and data release DR15.  In this case I was grabbing the maps and cubes remotely.

**Comment by havok2063** [comment] 2019-06-11 15:43
Great.  Thanks.  I will have a look and let you know.  Have you found this issue for many galaxies?

**Comment by roberid** [comment] 2019-06-11 15:56
Upon closer review, it seems to only be an issue when I am grabbing the maps and cube remotely.  If I do the same for data that I have downloaded and load it locally then all of the header IDs are correct.

**Comment by havok2063** [comment] 2019-06-11 16:21
Ok, thanks for the update.  There may be an issue with how the data is being retrieved from the database.

**Comment by albireox** [comment] 2019-06-12 15:30
This seems to happen for DR15 when I run it in remote mode. I have quickly checked the foreign keys in lore for `mangadapdb.file` `8949-12703` and it seems they are correctly linked to the right row in `mangadatadb.cube`. We'll need to dig a bit deeper into this. It's quite suspicious that the incorrect galaxy is `8485-1901` ...

**Comment by albireox** [comment] 2019-06-12 15:49
On a closer look, it seems the problem is with the header tables in `mangadapdb`. Apparently all our headers (or all the ones I've checked) are identical and equal to `8485-1901`. I have checked this through the Marvin classes, not directly with SQL queries because the header tables are complicated, but I cannot see anything in the model classes that would make it become hardcoded to `8485-1901`. This seems to be a loading problem.

**Comment by havok2063** [comment] 2019-06-12 16:03
Mmm, this somehow just feels right. 

I'll have a look at my loading scripts and the db tables.  It might be just some incorrect linking between db tables or maybe the actual content is incorrect in the db.  And we'll need to check this for MPL-8 and all the previous releases as well.

**Comment by havok2063** [comment] 2019-06-19 16:57
@roberid I think this has been resolved.  The issue was that many (but not all) of the DAP files for DR15 were accidentally loaded with the headers of the incorrect galaxy, `8485-1901`.   This is not a problem for MPL-8 or any of the other releases.  So it seems something went wrong only during the loading of MPL-7/DR15.  I reloaded all the headers for the mismatched galaxies.      

I tried the above example but you may want to try a few more galaxies.  If everything looks good to you, then I think we can close this.  

```
maps = marvin.tools.Maps(mangaid="1-404152")
cube = marvin.tools.Cube(mangaid="1-404152")

maps.header["MANGAID"]
'1-404152'

cube.header["MANGAID"]
'1-404152'

maps.header["PLATEIFU"]
'8949-12703'

cube.header["PLATEIFU"]
'8949-12703'
```

**Comment by roberid** [comment] 2019-06-25 20:28
Great.  Everything looks good to me.  Thanks guys

**Closed** 2019-06-25 20:58 UTC
Labels: bug, db, priority-medium
