### ISSUE TITLE
downloading problem

### ISSUE THREAD

**Issue by YiqingLiu** [sdss/marvin#460] opened 2018-07-19 16:37 UTC
**Describe the bug**
Cannot download DRP cubes on the server. 

**To Reproduce**
1. I firstly set up my ~/.netrc file and ran chmod 600 ~/.netrc 
2. Then I tried two approaches for downloading DRP cube. 
(1) Via Explicit Call
```
from marvin import config
config.setRelease('MPL-6')
from marvin.utils.general import downloadList
....
downloadList(MGid, dltype='cube')
```
(2) Via Tools
```
from marvin.tools.cube import Cube
from marvin import config
config.setRelease('MPL-6')
config.mode = 'local'
....
for i in arange(len(MGid)):
  cc = Cube(mangaid=MGid[i], download=True)

```
3. The (error) report from the two codes are: 
(1) 
```
[WARNING]: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
INFO: No release version set. Setting default to MPL-6
Sentry responded with an API error: RateLimited(Creation of this event was denied due to rate limiting)
['no DB connection found']
['no DB connection found']
['no DB connection found']
['no DB connection found']
['no DB connection found']
['no DB connection found']
....

```
(2) (In this case, there will be one cube downloaded in each run. In this example, the newly downloaded cube is 'manga-9050-12701-LOGCUBE.fits.gz')
```
[WARNING]: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
INFO: No release version set. Setting default to MPL-6
SDSS_ACCESS> syncing... please wait
SDSS_ACCESS> Done!
[WARNING]: ResourceWarning: subprocess 30657 is still running
[WARNING]: MarvinUserWarning: more than one plate-ifu found for mangaid=1-113567. Using the one with the highest SN2.
Sentry responded with an API error: RateLimited(Creation of this event was denied due to rate limiting)
['no DB connection found']
SDSS_ACCESS> syncing... please wait
SDSS_ACCESS> Done!
[WARNING]: ResourceWarning: subprocess 32050 is still running
Sentry responded with an API error: RateLimited(Creation of this event was denied due to rate limiting)
['no DB connection found']
SDSS_ACCESS> syncing... please wait
SDSS_ACCESS> Done!
[WARNING]: ResourceWarning: subprocess 33451 is still running
SDSS_ACCESS> syncing... please wait
SDSS_ACCESS> Done!
[WARNING]: ResourceWarning: subprocess 35321 is still running
Traceback (most recent call last):
  File "/mnt/zfsusers/YqL/.local/lib/python3.6/site-packages/marvin/tools/cube.py", line 159, in _load_cube_from_file
    self.data = fits.open(self.filename)
  File "/usr/local/shared/python/3.6.3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 164, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/usr/local/shared/python/3.6.3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 402, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/usr/local/shared/python/3.6.3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 986, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/usr/local/shared/python/3.6.3/lib/python3.6/site-packages/astropy/utils/decorators.py", line 487, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/shared/python/3.6.3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 175, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/usr/local/shared/python/3.6.3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 527, in _open_filename
    if not self._try_read_compressed(self.name, magic, mode, ext=ext):
  File "/usr/local/shared/python/3.6.3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 425, in _try_read_compressed
    self._file = gzip.GzipFile(**kwargs)
  File "/mnt/zfsusers/YqL/.local/lib/python3.6/site-packages/marvin/tools/spaxel.py", line 72, in spaxel_factory
    return type.__call__(cls, *args, **kwargs)
  File "/usr/local/shared/python/3.6.3/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/zfsusers/YqL/sas/mangawork/manga/spectro/redux/v2_3_1/9050/stack/manga-9050-12701-LOGCUBE.fits.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DRPdown1.py", line 58, in <module>
    cc = Cube(mangaid=MGid[i], download=True)
  File "/mnt/zfsusers/YqL/.local/lib/python3.6/site-packages/marvin/tools/spaxel.py", line 72, in spaxel_factory
    return type.__call__(cls, *args, **kwargs)
  File "/mnt/zfsusers/YqL/.local/lib/python3.6/site-packages/marvin/tools/cube.py", line 86, in __init__
    self._load_cube_from_file(data=self.data)
  File "/mnt/zfsusers/YqL/.local/lib/python3.6/site-packages/marvin/tools/cube.py", line 161, in _load_cube_from_file
    raise OSError('filename {0} cannot be found: {1}'.format(self.filename, err))
OSError: filename /mnt/zfsusers/YqL/sas/mangawork/manga/spectro/redux/v2_3_1/9050/stack/manga-9050-12701-LOGCUBE.fits.gz cannot be found: [Errno 2] No such file or directory: '/mnt/zfsusers/YqL/sas/mangawork/manga/spectro/redux/v2_3_1/9050/stack/manga-9050-12701-LOGCUBE.fits.gz'
```

**Comment by albireox** [comment] 2018-07-19 19:10
Hi @YiqingLiu,

Thanks for reporting this. First, sorry for the number of warnings and apparent errors in that log. Some of them, such as the SafeConfigParser have been fixed and won't show up in future version.

The Sentry error
```
Sentry responded with an API error: RateLimited(Creation of this event was denied due to rate limiting)
['no DB connection found']
```
is a known issue (see #436). Even if it seems like that, it is not an error and it won't make your command fail.

The problem that you see when using `download=True` from the Tools seems a real problem. I cannot reproduce it right now but it may be that the file is not yet at its location after being downloaded by the time `Cube` tries to load it. I'll have to dig a bit into this. Adding a larger delay between the end of the download and the moment when we try to open the file could help.

**Comment by YiqingLiu** [comment] 2018-07-19 23:22
Thanks, Jose. I just tried Explicit Call again. After a long list of ['no
DB connection found'], I got the error report below and found no cubes had
been downloaded. Could you please help?

Traceback (most recent call last):

  File
"/mnt/zfsusers/YqL/.local/lib/python3.6/site-packages/marvin/utils/general/general.py",
line 833, in downloadList

    rsync_access.set_stream()

  File
"/mnt/zfsusers/YqL/.local/lib/python3.6/site-packages/marvin/extern/sdss_access/python/sdss_access/sync/rsync.py",
line 74, in set_stream

    self.set_stream_task(task)

  File
"/mnt/zfsusers/YqL/.local/lib/python3.6/site-packages/marvin/extern/sdss_access/python/sdss_access/sync/rsync.py",
line 107, in set_stream_task

    out = self.get_task_out(task=task)

  File
"/mnt/zfsusers/YqL/.local/lib/python3.6/site-packages/marvin/extern/sdss_access/python/sdss_access/sync/rsync.py",
line 83, in get_task_out

    raise AccessError("Return code %r\n%s" % (status, err))

sdss_access.path.path.AccessError: Return code 10

b'rsync: getaddrinfo: dtn01.sdss.org 873: Temporary failure in name
resolution\nrsync error: error in socket IO (code 10) at
clientserver.c(124) [receiver=3.0.6]\n'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "DRPdown.py", line 53, in <module>

    downloadList(MGid, dltype='cube')

  File
"/mnt/zfsusers/YqL/.local/lib/python3.6/site-packages/marvin/utils/general/general.py",
line 835, in downloadList

    raise MarvinError('Error with sdss_access rsync.set_stream.
AccessError: {0}'.format(e))

marvin.core.exceptions.MarvinError: Error with sdss_access
rsync.set_stream. AccessError: Return code 10

b'rsync: getaddrinfo: dtn01.sdss.org 873: Temporary failure in name
resolution\nrsync error: error in socket IO (code 10) at
clientserver.c(124) [receiver=3.0.6]\n'.

You can submit this error to Marvin GitHub Issues (
https://github.com/sdss/marvin/issues/new).

Fill out a subject and some text describing the error that just occurred.

If able, copy and paste the full traceback information into the issue as
well.

Sentry is attempting to send 1 pending error messages

Waiting up to 10 seconds

Press Ctrl-C to quit

Sentry responded with an API error: RateLimited(Creation of this event was
denied due to rate limiting)

["AccessError: Return code 10\nb'rsync: getaddrinfo: dtn01.sdss.org 873:
Temporary failure in name resolution\\nrsync error: error in socket IO
(code 10) at clientserver.c(124) [receiver=3.0.6]\\n'", '  File
"marvin/utils/general/general.py", line 833, in downloadList', '  File
"sdss_access/sync/rsync.py", line 74, in set_stream', '  File
"sdss_access/sync/rsync.py", line 107, in set_stream_task', '  File
"sdss_access/sync/rsync.py", line 83, in get_task_out']


Yiqing

2018-07-19 20:10 GMT+01:00 José Sánchez-Gallego <notifications@github.com>:

**Comment by havok2063** [comment] 2018-07-19 23:37
Hi @YiqingLiu.  Which are country are you trying to use Marvin from?  We have had issues with people being unable to use `sdss_access`, which is the package Marvin uses to download data, from China, or similar countries, which may have a firewall.   

This section of your traceback makes me think that might be a possible reason.  
```
    raise MarvinError('Error with sdss_access rsync.set_stream.
AccessError: {0}'.format(e))

marvin.core.exceptions.MarvinError: Error with sdss_access
rsync.set_stream. AccessError: Return code 10

b'rsync: getaddrinfo: dtn01.sdss.org 873: Temporary failure in name
resolution\nrsync error: error in socket IO (code 10) at
clientserver.c(124) [receiver=3.0.6]\n'.
```
If this is the case, can you try again using a VPN?

**Comment by YiqingLiu** [comment] 2018-07-19 23:51
Thanks, Brian.

I am downloading the data using the server in Oxford now. How can I check
whether it is caused by the internet problems?

Yiqing

2018-07-20 0:37 GMT+01:00 Brian Cherinka <notifications@github.com>:

**Comment by havok2063** [comment] 2018-07-20 15:30
Hi @YiqingLiu, 

Can you try just straight rsyncing a file from the SAS from your terminal?  Something like

`rsync -avz rsync://sdss@dtn01.sdss.utah.edu/sas/mangawork/manga/spectro/redux/MPL-7/drpall-v2_4_3.fits .`

and let me know if that works?

**Comment by YiqingLiu** [comment] 2018-07-20 16:36
Hi Brian,

I just tested. It works.

Yiqing

2018-07-20 16:30 GMT+01:00 Brian Cherinka <notifications@github.com>:

**Comment by havok2063** [comment] 2018-07-20 17:51
Hi @YiqingLiu 

Ok, can you try this from within a fresh iPython terminal?

```
import marvin
from sdss_access import RsyncAccess
rsync = RsyncAccess(verbose=True)
rsync.remote()
rsync.add('drpall', drpver='v2_3_1')
rsync.set_stream()
rsync.commit()
```
If that works, can you also try the same thing but change the `rsync.add` line to 

`rsync.add('mangacube', drpver='v2_3_1', plate=8485, ifu=1901)
`

Can you also provide an example of what your `MGid` parameter is you're passing into `downloadList`?

**Comment by havok2063** [comment] 2018-07-23 15:52
Hi @YiqingLiu.   It looks like the two tests worked.  

Just a note on adding code in Github issues.  When adding code either copied from the terminal, or manually, to preserve the syntax, you can mark it as code using the "<>" option.  Just highlight the lines, and click that button, and it will place that text inside a code block.  This improves readability and maintains code syntax.  See previous posts in this thread.  You can also wrap single words or sentences in `` to convert to code syntax.

From these tests it looks like you were able to successfully download a `Cube` using `sdss_access` directly.   

Is your MGid list exactly like the syntax in your post, i.e. `['1-286558' '1-274706'
'1-201874' '1-626658' '1-24425']`?  The input needs to be a comma-separated list of plateifus or mangaids.  Can you try using `mgids = ['1-286558', '1-274706', '1-201874', '1-626658', '1-24425']` instead?   If it still fails, we will back up and do a few more tests.

**Comment by YiqingLiu** [comment] 2018-07-25 18:41
Thanks, Brian. And apologise for the inconvenience. I will improve my
edition on Github in the future.

The reason of the missing comma in the list I showed you is that MGid is an
array, and there are no commas in between when I print the array out. I
tried to covert MGid into a list mgids, and got the same error reports.
However, the downloading worked when I sliced MGid or mgids, i.e., input
MGid[m:n] or mgids[m:n]. Do you see any clues from this?

In the end, if Marvin cannot work eventually, could you please provide a
rsync command to download DRP cubes? Are there any difference in DRP cubes
between the MPL-6 and MPL-7? Many thanks.

Yiqing

2018-07-23 16:52 GMT+01:00 Brian Cherinka <notifications@github.com>:

**Comment by havok2063** [comment] 2018-07-26 19:22
Hi @YiqingLiu 

I used your list of manga-ids, both as an input Python list, and as a numpy array, and I was able to download the cubes successfully.  So it is possible.  Can you try the following 

```
from marvin import config
from marvin.utils.general import downloadList
config.setRelease('MPL-6')

ids = ['1-209232']
downloadList(ids, dltype='cube')
```
This should essentially run the same command that you ran three comments back.  If that works can you please try your original command again

```
from marvin import config
from marvin.utils.general import downloadList
config.setRelease('MPL-6')

mgids = ['1-286558', '1-274706', '1-201874', '1-626658', '1-24425']
downloadList(mgids, dltype='cube')
```
What's new for MPL-7 is indicated on the wiki here, https://trac.sdss.org/wiki/MANGA/TRM/TRM_MPL-7/whatsnew
MPL-7 will be available in Marvin soon.

**Comment by YiqingLiu** [comment] 2018-07-30 00:11
Thanks, Brian. Both these tests ran successfully. 

I also tried some sliced input arrays / lists, e.g. MGid[m:n] or mgids[m:n], where m,n are integers. They are always successful. 

However, once I input the entire array / list of MGid / mgids, it would fail. 
I also tried to save the IDs in a text file using 'savetxt' command and read it using 'loadtxt'. Then put the read array into downloadList. And it still failed. I checked the file of ID list but found nothing wrong. 

I show my complete code below, could you please help to test it? 

```
from pylab import *
from astropy.io import fits

from marvin import config
config.setRelease('MPL-6')
from marvin.utils.general import downloadList

sampTabHDU = fits.open('drpall-v2_3_1.fits')
sampTab = sampTabHDU[1].data

MGid0 = sampTab['mangaid']
IAUid0 = sampTab['nsa_iauname']
Ms0 = sampTab['nsa_sersic_mass']  # stellar mass
re0 = sampTab['nsa_sersic_th50']  # arcsec
zz0 = sampTab['nsa_z']
cc,H0 = 299792.458, 73.52 # km/s, km/s/Mpc
DD0 = cc*zz0/H0 # Mpc
Re0 = 1e3*DD0*re0/206265.  # kpc

jj = (Re0>0) & (Ms0>0) 
MGid,IAUid = MGid0[jj],IAUid0[jj]

downloadList(MGid, dltype='cube')
```

**Comment by havok2063** [comment] 2018-07-30 17:12
Hi @YiqingLiu ,

Your code looks ok to me.  I've looked at it and there's nothing wrong with your `MGid` array.  It works when I slice the array to something smaller.  This array has ~4700 objects in it in total.  My only thought might be that `sdss_access` cannot handle that many objects, and is crashing somewhere along the way.  

@joelbrownstein Do you have any ideas on what the problem could be here?  Is there a max number of tasks `sdss_access` can handle?  The relevant error from the above traceback is 

```
sdss_access.path.path.AccessError: Return code 10
b'rsync: getaddrinfo: dtn01.sdss.org 873: Temporary failure in name
resolution\nrsync error: error in socket IO (code 10) at
clientserver.c(124) [receiver=3.0.6]\n'
```
Do you know what could be causing this error?

**Comment by YiqingLiu** [comment] 2018-07-30 21:02
Thanks, Brian. Look forward to the answer from Joel.

I just found MPL-7 is more suitable for my study. However, the DRP cubes
are not available for Marvin at present, and I haven't figured out how to
download them by 'rsync' command. Could you please help?

Yiqing

2018-07-30 18:12 GMT+01:00 Brian Cherinka <notifications@github.com>:

**Comment by joelbrownstein** [comment] 2018-08-01 06:02
sdss_access has no max number of tasks.  the error message is not from sdss_access.  what happens when you rerun the same command?  does rsync keep going, and complete ?

**Comment by YiqingLiu** [comment] 2018-08-02 23:52
Thanks, Joel.

I split my list into 300 galaxies for each call, and only started the next
run after the last 300 galaxies finished being downloaded. (Otherwise I
would get the error report as I presented in the beginning.)
Now I have gotten the entire MPL-6 sample of 4609 galaxies.

Yiqing

2018-08-01 7:03 GMT+01:00 Joel Brownstein <notifications@github.com>:

**Comment by havok2063** [comment] 2018-08-03 01:45
Hi @YiqingLiu.  That's great.  I'm glad it eventually worked for you.  Maybe rsync has a problem handling ~4600 files at the same time.  Just out of curiosity, how long did it take you to download everything?

**Comment by havok2063** [comment] 2018-08-08 18:07
Ok, no worries.  I think we can safely close this now.

**Closed by havok2063** 2018-08-08 18:07 UTC
Labels: bug, marvin-tools, needs-reproduction
