### ISSUE TITLE
getImagesByList() in Image Utilities does not return files

### ISSUE THREAD

**Issue by sjshamsi** [sdss/marvin#420] opened 2018-06-29 20:40 UTC
I was running the getImagesByList() function in Image Utilities to get a list of image files, but when I try to run the code on the Marvin 2.2.5 Documentation page [here](https://sdss-marvin.readthedocs.io/en/stable/utils/images.html), I run into an error: 
```from marvin.utils.general.images import getImagesByList

# make a list of targets, can be plateifus or manga-ids
plateifus = ['8485-1901', '7443-12701']

# download the images for the targets in my list from Utah into my local SAS
images = getImagesByList(plateifus, mode='remote', download=True)

# search my local SAS filesystem for images in the input list
images = getImagesByList(plateifus, mode='local')
print(images)

SDSS_ACCESS> syncing... please wait
SDSS_ACCESS> Done!
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/.local/lib/python3.5/site-packages/marvin/utils/general/images.py in getDir3d(inputid, mode, release)
     86         try:
---> 87             plate = Plate(plate=plateid, nocubes=True, mode=mode, release=release)
     88         except Exception as e:

~/.local/lib/python3.5/site-packages/marvin/tools/spaxel.py in spaxel_factory(cls, *args, **kwargs)
     71     if cls is not SpaxelBase:
---> 72         return type.__call__(cls, *args, **kwargs)
     73 

~/.local/lib/python3.5/site-packages/marvin/tools/plate.py in __init__(self, input, filename, mangaid, plateifu, mode, data, release, plate, download, nocubes)
    120                                   plateifu=plateifu, mode=mode, data=data, release=release,
--> 121                                   download=download)
    122 

~/.local/lib/python3.5/site-packages/marvin/core/core.py in __init__(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download)
    154         if self.mode == 'local':
--> 155             self._doLocal()
    156         elif self.mode == 'remote':

~/.local/lib/python3.5/site-packages/marvin/core/core.py in _doLocal(self)
    285                     if self._forcedownload:
--> 286                         self.download()
    287                         self.data_origin = 'file'

~/.local/lib/python3.5/site-packages/marvin/core/core.py in download(self, pathType, **pathParams)
    314             rsync_access.remote()
--> 315             rsync_access.add(pathType, **pathParams)
    316             rsync_access.set_stream()

~/.local/lib/python3.5/site-packages/marvin/extern/sdss_access/python/sdss_access/sync/rsync.py in add(self, filetype, **kwargs)
     53 
---> 54         location = self.location(filetype, **kwargs)
     55         source = self.url(filetype, sasdir='sas' if not self.public else '', **kwargs)

~/.local/lib/python3.5/site-packages/marvin/extern/sdss_access/python/sdss_access/path/path.py in location(self, filetype, base_dir, **kwargs)
    354 
--> 355         if '//' in location:
    356             location = location.replace('//', '/')

TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

MarvinError                               Traceback (most recent call last)
<ipython-input-43-058028b3608b> in <module>()
      8 
      9 # search my local SAS filesystem for images in the input list
---> 10 images = getImagesByList(plateifus, mode='local')
     11 print(images)

~/.local/lib/python3.5/site-packages/marvin/utils/general/images.py in wrapper(*args, **kwargs)
     64             raise MarvinError('sdss_access is not installed')
     65         else:
---> 66             return func(*args, **kwargs)
     67     return wrapper
     68 

~/.local/lib/python3.5/site-packages/marvin/utils/general/images.py in wrapper(*args, **kwargs)
     52             kwargs['mode'] = marvin.config.mode
     53         assert kwargs['mode'] in ['auto', 'local', 'remote'], 'Mode must be either auto, local, or remote'
---> 54         return func(*args, **kwargs)
     55     return wrapper
     56 

~/.local/lib/python3.5/site-packages/marvin/utils/general/images.py in getImagesByList(inputlist, download, mode, as_url, verbose, release)
    330         listofimages = []
    331         for plateifu in inputlist:
--> 332             dir3d = getDir3d(plateifu, mode=mode, release=release)
    333             plateid, ifu = plateifu.split('-')
    334             if as_url:

~/.local/lib/python3.5/site-packages/marvin/utils/general/images.py in getDir3d(inputid, mode, release)
     88         except Exception as e:
     89             raise MarvinError('Could not retrieve a remote plate.  If it is a mastar '
---> 90                               'plate you are after, Marvin currently does not handle those: {0}'.format(e))
     91         else:
     92             dir3d = plate.dir3d

MarvinError: Could not retrieve a remote plate.  If it is a mastar plate you are after, Marvin currently does not handle those: argument of type 'NoneType' is not iterable.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.
```
I expecting a list to return when I ran the following code, but `print(images)` returns `None`.
```from marvin.utils.general.images import getImagesByList
plateifus = ['8485-1901', '7443-12701']
images = getImagesByList(plateifus, mode='remote', download=True)

print(images)
None
```

**Desktop**
 - Windows 10
 - Chrome (running on Jupyter Notebooks)
 - Marvin 2.2.5

**Comment by havok2063** [comment] 2018-06-30 22:39
Marvin was designed and tested for Mac and Linux systems.  Since you're using Windows, this could be a problem related to file path construction.  Marvin can be installed on Windows machines but it has not been fully tested, and not all functionality may work as expected.  We certainly haven't tested everything on Windows machines.  The underlying issue looks like it's with another piece of code called `sdss_access`.  We can try to have a look at testing that bit on a Windows machine.

**Comment by sjshamsi** [comment] 2018-07-03 19:49
I was able to run the code on my Windows laptop through a Jupyter server (Jupyterhub  version 0.8.1 running on an Ubuntu Linux version 16.04 server), and got the images via the getImagesByList() function.
``` from marvin.utils.general.images import getImagesByList
from marvin.utils.general.images import showImage

plateifus = ['8485-1901', '7443-12701']

images = getImagesByList(plateifus, mode='remote', download=True)

SDSS_ACCESS> syncing... please wait
SDSS_ACCESS> Done!

images

['/homes/sshamsi/sas/mangawork/manga/spectro/redux/v2_3_1/8485/stack/images/1901.png',
 '/homes/sshamsi/sas/mangawork/manga/spectro/redux/v2_3_1/7443/stack/images/12701.png']
```
After this it continued to return `None` again, even on a Linux desktop even with different plate IFUs. This changed when we change the `download` parameter to `Flase`, and the code returned images on the Jupyter server after that.
```from marvin.utils.general.images import getImagesByList
from marvin.utils.general.images import showImage

plateifus = ['8568-12704', '8156-3701']

images = getImagesByList(plateifus, mode='remote', download=False)

print(images)

['/homes/sshamsi/sas/mangawork/manga/spectro/redux/v2_3_1/8568/stack/images/12704.png', '/homes/sshamsi/sas/mangawork/manga/spectro/redux/v2_3_1/8156/stack/images/3701.png']
```

However, I still wasn't able to find them in the local mode after having downloaded them, and the following problem persists both on Windows and Linux computers with Jupyter on a Linux server:
```img = getImagesByList(plateifus, mode='local')

---------------------------------------------------------------------------
MarvinError                               Traceback (most recent call last)
~/.local/lib/python3.5/site-packages/marvin/utils/general/images.py in getDir3d(inputid, mode, release)
     86         try:
---> 87             plate = Plate(plate=plateid, nocubes=True, mode=mode, release=release)
     88         except Exception as e:

~/.local/lib/python3.5/site-packages/marvin/tools/spaxel.py in spaxel_factory(cls, *args, **kwargs)
     71     if cls is not SpaxelBase:
---> 72         return type.__call__(cls, *args, **kwargs)
     73 

~/.local/lib/python3.5/site-packages/marvin/tools/plate.py in __init__(self, input, filename, mangaid, plateifu, mode, data, release, plate, download, nocubes)
    120                                   plateifu=plateifu, mode=mode, data=data, release=release,
--> 121                                   download=download)
    122 

~/.local/lib/python3.5/site-packages/marvin/core/core.py in __init__(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download)
    154         if self.mode == 'local':
--> 155             self._doLocal()
    156         elif self.mode == 'remote':

~/.local/lib/python3.5/site-packages/marvin/core/core.py in _doLocal(self)
    288                     else:
--> 289                         raise MarvinError('this is the end of the road. '
    290                                           'Try using some reasonable inputs.')

MarvinError: this is the end of the road. Try using some reasonable inputs..
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

During handling of the above exception, another exception occurred:

MarvinError                               Traceback (most recent call last)
<ipython-input-19-7c3b93e814d6> in <module>()
----> 1 img = getImagesByList(plateifus, mode='local')

~/.local/lib/python3.5/site-packages/marvin/utils/general/images.py in wrapper(*args, **kwargs)
     64             raise MarvinError('sdss_access is not installed')
     65         else:
---> 66             return func(*args, **kwargs)
     67     return wrapper
     68 

~/.local/lib/python3.5/site-packages/marvin/utils/general/images.py in wrapper(*args, **kwargs)
     52             kwargs['mode'] = marvin.config.mode
     53         assert kwargs['mode'] in ['auto', 'local', 'remote'], 'Mode must be either auto, local, or remote'
---> 54         return func(*args, **kwargs)
     55     return wrapper
     56 

~/.local/lib/python3.5/site-packages/marvin/utils/general/images.py in getImagesByList(inputlist, download, mode, as_url, verbose, release)
    330         listofimages = []
    331         for plateifu in inputlist:
--> 332             dir3d = getDir3d(plateifu, mode=mode, release=release)
    333             plateid, ifu = plateifu.split('-')
    334             if as_url:

~/.local/lib/python3.5/site-packages/marvin/utils/general/images.py in getDir3d(inputid, mode, release)
     88         except Exception as e:
     89             raise MarvinError('Could not retrieve a remote plate.  If it is a mastar '
---> 90                               'plate you are after, Marvin currently does not handle those: {0}'.format(e))
     91         else:
     92             dir3d = plate.dir3d

MarvinError: Could not retrieve a remote plate.  If it is a mastar plate you are after, Marvin currently does not handle those: this is the end of the road. Try using some reasonable inputs..
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well..
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

Sentry responded with an API error: RateLimited(Creation of this event was denied due to rate limiting)
['this is the end of the road. Try using some reasonable inputs.']
Sentry responded with an API error: RateLimited(Creation of this event was denied due to rate limiting)
['MarvinError: this is the end of the road. Try using some reasonable inputs..\nYou can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).\nFill out a subject and some text describing the error that just occurred.\nIf able, copy and paste the full traceback information into the issue as well.', '  File "marvin/utils/general/images.py", line 87, in getDir3d', '  File "marvin/tools/spaxel.py", line 72, in spaxel_factory', '  File "marvin/tools/plate.py", line 121, in __init__', '  File "marvin/core/core.py", line 155, in __init__', '  File "marvin/core/core.py", line 289, in _doLocal']
```

**Comment by havok2063** [comment] 2019-11-27 17:19
With the completion and merge of PR #652, Marvin should now more robustly work on Windows machines.  The updates will be available in the next release of Marvin.  The API limit will also be removed in the coming update. Closing this for now.

**Closed by havok2063** 2019-11-27 17:19 UTC
Labels: bug, needs-reproduction, windows
