### ISSUE TITLE
Can't get the SDSS image using Marvin tools

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#519] opened 2018-08-21 20:01 UTC
**Describe the bug**

I'm checking the tutorial in the SDSS web and I'm getting an error when plotting the SDSS image of a MaNGA galaxy. 

**To Reproduce**
Steps to reproduce the behaviour:

I'm running the tutorial https://testng.sdss.org/dr15/manga/manga-tutorials/marvin-tutorial/marvin-tools/ in a jupyter notebook.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-5eb4cfc79873> in <module>()
----> 1 image = showImage(plateifu='7443-12703', show_image=False)
      2 fig, ax = plt.subplots()
      3 ax.imshow(image)
      4 ax.axis('off')

~/anaconda/envs/python3/lib/python3.6/site-packages/marvin/utils/general/images.py in wrapper(*args, **kwargs)
     64             raise MarvinError('sdss_access is not installed')
     65         else:
---> 66             return func(*args, **kwargs)
     67     return wrapper
     68 

~/anaconda/envs/python3/lib/python3.6/site-packages/marvin/utils/general/images.py in wrapper(*args, **kwargs)
     52             kwargs['mode'] = marvin.config.mode
     53         assert kwargs['mode'] in ['auto', 'local', 'remote'], 'Mode must be either auto, local, or remote'
---> 54         return func(*args, **kwargs)
     55     return wrapper
     56 

~/anaconda/envs/python3/lib/python3.6/site-packages/marvin/utils/general/images.py in showImage(path, plateifu, release, return_image, show_image, mode)
    467     # Open the image
    468     try:
--> 469         image = PIL.Image.open(fileobj)
    470     except IOError as e:
    471         print('Error: cannot open image')

AttributeError: module 'PIL' has no attribute 'Image'

```
**Expected behaviour**

To plot the SDSS image of a MaNGA galaxy

**Screenshots**

**Desktop (please complete the following information):**
OS X
 - Browser [e.g. chrome, safari]  safari
 - Version of Marvin [e.g. 2.0.2] 
2.2.6

**Additional context**

I'm not getting this error in a terminal in ubuntu.

**Comment by havok2063** [comment] 2018-08-23 21:35
I cannot reproduce this using marvin `2.2.6` in a fresh environment.

**Comment by albireox** [comment] 2018-11-12 19:09
At some point the PIL library changed (now it's called `pillow`) and the API somehow changed. Not sure if that's an issue here.

**Comment by havok2063** [comment] 2018-11-20 23:55
Closing this.  The `showImage` tool is deprecated.  `pillow` is a `PIL` fork.  Here is the documentation on installing `pillow`.  https://pillow.readthedocs.io/en/5.3.x/installation.html.   marvin has the correct package in its requirements.  We've never supported the old `PIL` package.  `Pillow v2.0+` supports the `Image` class tool.   All users should make sure they are using the correct package.  According to their docs, `PIL` and `Pillow` cannot coexist.

**Closed by havok2063** 2018-11-20 23:55 UTC
Labels: needs-reproduction
