### ISSUE TITLE
Data accessing and not found error

### ISSUE THREAD

**Issue by yuanzeluo** [sdss/marvin#698] opened 2020-02-25 22:21 UTC
Hi, I'm trying to use marvin to access maps and spectra for a lot of galaxies/spaxels. While looping, I always get following errors:
<img width="998" alt="Screen Shot 2020-02-25 at 12 37 53" src="https://user-images.githubusercontent.com/28064192/75292097-877be500-57f1-11ea-9e6b-3709b29b1ca5.png">
<img width="991" alt="Screen Shot 2020-02-25 at 15 02 39" src="https://user-images.githubusercontent.com/28064192/75292101-89de3f00-57f1-11ea-9f91-de81e3da7f4d.png">

The plate number that is producing the not found error is different each time, so I don't think it's the problem of a specific plate.

**To Reproduce**
Some code that I used which produced the errors
```
from marvin.tools.maps import Maps
from marvin.tools.cube import Cube
from marvin.tools.modelcube import ModelCube

# configure the data release/version
release = 'MPL-8' 
config.access = 'collab'
config.setRelease(release)

# login to receive a token
config.login()

cube_dict={}
for g in gal_:
        c=Cube(plateifu=g, mode='remote')
        cube_dict[g]=c

inside some for loop:
    cube_=cube_dict[pid]
    l=cube_[sp_i, sp_j].flux.pixmask.bits
    f=cube_[sp_i, sp_j].flux.value
```

**Desktop (please complete the following information):**
 - Version of Marvin: 2.3.5 (should be the latest version as of 2/25/2020

Any suggestions on how to get rid of these errors? Thank you very much!

**Comment by havok2063** [comment] 2020-04-24 14:13
@yuanzeluo Can you copy and paste the full traceback?  I'll have a better sense of what the problem is then.  Does the error occur at exactly the same place each time?  What line of code does it occur on?  How many galaxies do you loop through before the error occurs?   Can you explain a bit more what the problem you're trying to solve is?

**Comment by havok2063** [comment] 2021-12-07 21:46
Closing this.  Try updating to the latest marvin.   If it's still an issue, we can open a new ticket.

**Closed by havok2063** 2021-12-07 21:46 UTC
