### ISSUE TITLE
Current implementation of MMA fails because datamodel not set

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#517] opened 2018-08-13 06:02 UTC
**Describe the bug**
The current implementation of MMA sets the datamodel *after* the MMA, which makes Maps and ModelCube fail because they depend on the datamodel being set to run `getFullPath()`.

**To Reproduce**
1. Have the default Maps file for 8485-1901
2. 
```
import marvin
marvin.config.forceDbOff()
maps = marvin.tools.Maps('8485-1901', mode='local')
-----------------------------------------------------------------------
RecursionError                        Traceback (most recent call last)
<ipython-input-5-b64ad2fb1362> in <module>()
----> 1 maps = marvin.tools.Maps('8485-1901', mode='local')

~/Documents/Repo/manga/marvin/python/marvin/tools/spaxel.py in spaxel_factory(cls, *args, **kwargs)
     62
     63     if cls is not SpaxelBase:
---> 64         return type.__call__(cls, *args, **kwargs)
     65
     66     cube = kwargs.pop('cube', None)

~/Documents/Repo/manga/marvin/python/marvin/tools/maps.py in __init__(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download, nsa_source, bintype, template, template_kin)
     96                                   mangaid=mangaid, plateifu=plateifu,
     97                                   mode=mode, data=data, release=release,
---> 98                                   drpall=drpall, download=download)
     99
    100         NSAMixIn.__init__(self, nsa_source=nsa_source)

~/Documents/Repo/manga/marvin/python/marvin/tools/core.py in __init__(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download)
    116         MMAMixIn.__init__(self, input=input, filename=filename, mangaid=mangaid,
    117                           plateifu=plateifu, mode=mode, data=data, release=release,
--> 118                           download=download)
    119
    120         self.datamodel = None

~/Documents/Repo/manga/marvin/python/marvin/tools/mixins/mma.py in __init__(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download, ignore_db)
    122
    123         if self.mode == 'local':
--> 124             self._doLocal()
    125         elif self.mode == 'remote':
    126             self._doRemote()

~/Documents/Repo/manga/marvin/python/marvin/tools/mixins/mma.py in _doLocal(self)
    269                 self.data_origin = 'db'
    270             else:
--> 271                 fullpath = self._getFullPath()
    272
    273                 if fullpath and os.path.exists(fullpath):

~/Documents/Repo/manga/marvin/python/marvin/tools/maps.py in _getFullPath(self)
    195         """Returns the full path of the file in the tree."""
    196
--> 197         params = self._getPathParams()
    198         path_type = params.pop('path_type')
    199

~/Documents/Repo/manga/marvin/python/marvin/tools/maps.py in _getPathParams(self)
    221         plate, ifu = self.plateifu.split('-')
    222
--> 223         if self.datamodel.release == 'MPL-4':
    224             niter = int('{0}{1}'.format(self.template.n, self.bintype.n))
    225             params = dict(drpver=self._drpver, dapver=self._dapver,

~/Documents/Repo/manga/marvin/python/marvin/tools/maps.py in __getattr__(self, value)
    135     def __getattr__(self, value):
    136
--> 137         if isinstance(value, six.string_types) and value in self.datamodel:
    138             return self.getMap(value)
    139

... last 1 frames repeated, from the frame below ...

~/Documents/Repo/manga/marvin/python/marvin/tools/maps.py in __getattr__(self, value)
    135     def __getattr__(self, value):
    136
--> 137         if isinstance(value, six.string_types) and value in self.datamodel:
    138             return self.getMap(value)
    139

RecursionError: maximum recursion depth exceeded in __instancecheck__
```

**Expected behavior**
No error.

**Additional context**
The solution is to probably move the lines

```python
self.datamodel = None
self._set_datamodel()
```

from `MarvinToolsClass` to `MMAMixIn`, and move the empty `_set_datamodel` there as well (and not make it an abstract method). Although at that point it's not clear whether `MarvinToolsClass` is a core class at all or a mixing that should be split in a few functionalities (interaction, pickling, etc.)

This is also preventing the docs from building.

**Comment by havok2063** [comment] 2018-08-19 21:03
This has been fixed in master.  This solution was easy enough to implement.  Although I don't think the datamodel should be a part of the MMA, I couldn't come up with a better workaround.  I think the datamodel belongs in the `MarvinToolsClass`.  The issue is the `getFullPath` for `Maps` depends on the datamodel.  I don't know if it should but I understand why it's like that.  We also don't seem to use it with the `ModelCube` in the same way, even though it has the same issue. 

We could split up the `MarvinToolsClass` but there's not much left there to split up.  It's already essentially acting as a mixin.  For me, the remaining content kind of works all together.  Unless we have plans to expand pickling, flags, etc, I suggest we keep things together now and split things out into individual mixins as we need to.

**Comment by albireox** [comment] 2018-08-23 18:46
Had a look and this seems fine with me. We can try to find a better implementation for Marvin 3 but I think this is what we need for now.

**Comment by havok2063** [comment] 2018-08-23 21:27
Sounds good.  Closing for now.

**Closed by havok2063** 2018-08-23 21:27 UTC
Labels: bug, priority-high
