### ISSUE TITLE
Inverted coordinates in maps

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#181] opened 2017-02-17 13:14 UTC
Hi, 

The spaxel coordinates in the maps are inverted. For example, look at galaxy 8081-12705, the SDSS image shows a star, if you click on the star you see the spectra of the star. Now ask, for instance, for bin_mflux map for the voronoi binning cube. Now the star is a the right, but if you click, the spectra is not the spectra of the star. If you want to see the spectra of the star you have to click in the position where the star is located according the SDSS image.

**Comment by bretthandrews** [comment] 2017-02-17 15:39
This is probably connected to our fix #156 for Issue #148

**Comment by havok2063** [comment] 2017-02-17 16:11
This should be fixed.  If not, then it needs confirmation and reproduction.

**Comment by bretthandrews** [comment] 2017-02-17 16:12
It's definitely there, which is why I removed the needs-reproduction label. I can also see it in my local web. I'm working on it in the webmaps branch.

**Comment by havok2063** [comment] 2017-02-17 16:13
Oh ok.  Then I guess something is still messed up.  It could be inherit in the db.   That may be the best place to fix it.  If we can pin down that it's coming from there.

**Comment by bretthandrews** [comment] 2017-02-17 16:27
I checked a spaxel in my local DB and on Utah. I think that the DB is correct and the web display is inverted.

**Comment by havok2063** [comment] 2017-02-17 16:29
How does it compare to the Tools display since they both use tool features to grab the data?

**Comment by bretthandrews** [comment] 2017-02-17 16:30
They're inverted from each other

**Comment by havok2063** [comment] 2017-02-17 16:31
ok

**Comment by havok2063** [comment] 2017-02-18 18:17
This is now fixed.

**Closed by havok2063** 2017-02-18 18:17 UTC
Labels: bug, marvin-web, priority-high
